package com.example.boardgamescoretrackerv2;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

// This is where the 'Game' table (entity) of the database is defined.
@Entity(tableName = "game_table")
public class Game {

    // ID for each Game instance is autogenerated


    @PrimaryKey
    @NonNull
    @ColumnInfo(name = "game")
    private String mGame;

    public Game(@NonNull String game) {this.mGame = game;}

    // Getter method:
    public String getGame(){return this.mGame;}



}