package com.example.boardgamescoretrackerv2;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

// This is where the 'Game' table (entity) of the database is defined.
@Entity
public class Game {

    // ID for each Game instance is autogenerated
    @PrimaryKey(autoGenerate = true)
    public int gameId;

    @ColumnInfo(name = "game_name")
    public String gameName;

}