package com.example.boardgamescoretrackerv2;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

// This is where the 'Game' table (entity) of the database is defined.
@Entity(tableName = "game_table")
public class Game {

    // ID for each Game instance is autogenerated
    @PrimaryKey(autoGenerate = true)
    private int gameId;

    @NonNull
    private String gameName;

    // Constructor method:
    public Game(@NonNull String gameName) {
        this.gameName = gameName;
    }

    // Getter methods:
    public int getGameId(){return this.gameId;}
    @NonNull
    public String getGameName(){return this.gameName;}

    // Setter:
    public void setGameId(int gameId){ this.gameId = gameId; }

}