package com.example.boardgamescoretrackerv2;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

// The 'Player' table (entity) of the app's database is defined here.
@Entity(tableName = "player_table")
public class Player {

    // ID for each Player instance is autogenerated
    @PrimaryKey(autoGenerate = true)
    private int playerId;

    @NonNull
    private String playerName;

    // Constructor method:
    public Player(@NonNull String playerName) {
        this.playerName = playerName;
    }

    // Getter methods:
    public int getPlayerId(){return this.playerId;}
    @NonNull
    public String getPlayerName(){return this.playerName;}

    // Setter:
    public void setPlayerId(int playerId){ this.playerId = playerId; }

}
